import { jsPDF } from "jspdf";
import type { ExecutionArtifact } from "@/types/execution";
import type {
  TextArtifactData,
  ImageArtifactData,
  KpiArtifactData,
  TableArtifactData,
} from "@/types/execution";

// ─── Colors ──────────────────────────────────────────────────────────────────

const COLORS = {
  primary: [79, 138, 255] as [number, number, number],
  dark: [7, 7, 13] as [number, number, number],
  text: [240, 240, 245] as [number, number, number],
  muted: [152, 152, 176] as [number, number, number],
  accent: [16, 185, 129] as [number, number, number],
  border: [40, 40, 60] as [number, number, number],
  bg: [18, 18, 30] as [number, number, number],
};

interface ReportInput {
  workflowName: string;
  artifacts: Map<string, ExecutionArtifact>;
  nodeLabels: Map<string, string>;
  executedAt?: Date;
}

export async function generatePDFReport({
  workflowName,
  artifacts,
  nodeLabels,
  executedAt,
}: ReportInput): Promise<void> {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pw = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pw - margin * 2;
  let y = margin;

  // ─── Helper: add new page if needed ─────────────────────────────────────
  function ensureSpace(needed: number) {
    if (y + needed > ph - 25) {
      doc.addPage();
      y = margin;
      addPageFooter();
    }
  }

  function addPageFooter() {
    const pageNum = doc.getNumberOfPages();
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.muted);
    doc.text(`Page ${pageNum}`, pw / 2, ph - 10, { align: "center" });
    doc.text("Generated by BuildFlow", pw - margin, ph - 10, { align: "right" });
  }

  // ─── Cover / Header ────────────────────────────────────────────────────
  // Gradient-like header bar
  doc.setFillColor(...COLORS.primary);
  doc.rect(0, 0, pw, 65, "F");

  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.text("BuildFlow Report", margin, 20);

  doc.setFontSize(13);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(220, 230, 255);
  doc.text("CONCEPT DESIGN REPORT", margin, 30);

  doc.setFontSize(11);
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "normal");
  doc.text(workflowName, margin, 42);

  const dateStr = (executedAt ?? new Date()).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
  doc.setFontSize(9);
  doc.text(dateStr, pw - margin, 42, { align: "right" });

  y = 77;

  // ─── Summary section ──────────────────────────────────────────────────
  doc.setFontSize(14);
  doc.setTextColor(50, 50, 60);
  doc.setFont("helvetica", "bold");
  doc.text("Execution Summary", margin, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 100);
  doc.text(`Nodes executed: ${artifacts.size}`, margin, y);
  y += 5;
  doc.text(`Workflow: ${workflowName}`, margin, y);
  y += 5;
  doc.text(`Date: ${dateStr}`, margin, y);
  y += 12;

  // ─── Divider ─────────────────────────────────────────────────────────
  doc.setDrawColor(...COLORS.border);
  doc.setLineWidth(0.3);
  doc.line(margin, y, pw - margin, y);
  y += 10;

  // ─── Table of Contents ──────────────────────────────────────────────
  const entries = Array.from(artifacts.entries());

  doc.setFontSize(14);
  doc.setTextColor(50, 50, 60);
  doc.setFont("helvetica", "bold");
  doc.text("Table of Contents", margin, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 100);
  for (let tocIdx = 0; tocIdx < entries.length; tocIdx++) {
    const [tocTileId] = entries[tocIdx];
    const tocLabel = nodeLabels.get(tocTileId) ?? "Node Output";
    ensureSpace(6);
    doc.text(`${tocIdx + 1}. ${tocLabel}`, margin + 4, y);
    y += 6;
  }
  y += 12;

  doc.setDrawColor(...COLORS.border);
  doc.setLineWidth(0.3);
  doc.line(margin, y, pw - margin, y);
  y += 10;

  // ─── Each artifact ───────────────────────────────────────────────────

  for (let idx = 0; idx < entries.length; idx++) {
    const [tileId, artifact] = entries[idx];
    const label = nodeLabels.get(tileId) ?? "Node Output";

    ensureSpace(30);

    // Section header
    doc.setFontSize(12);
    doc.setTextColor(50, 50, 60);
    doc.setFont("helvetica", "bold");
    doc.text(`${idx + 1}. ${label}`, margin, y);

    // Type badge
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.primary);
    doc.text(artifact.type.toUpperCase(), pw - margin, y, { align: "right" });
    y += 7;

    // Render based on type
    switch (artifact.type) {
      case "text":
        y = renderText(doc, artifact.data as TextArtifactData, margin, y, contentWidth);
        break;
      case "image":
        y = await renderImage(doc, artifact.data as ImageArtifactData, margin, y, contentWidth);
        break;
      case "kpi":
        y = renderKpis(doc, artifact.data as KpiArtifactData, margin, y, contentWidth);
        break;
      case "table":
        y = renderTable(doc, artifact.data as TableArtifactData, margin, y, contentWidth);
        break;
      case "json":
        y = renderJson(doc, artifact.data, margin, y, contentWidth);
        break;
      default:
        doc.setFontSize(9);
        doc.setTextColor(...COLORS.muted);
        doc.text(`[${artifact.type} artifact — see app for details]`, margin, y);
        y += 6;
    }

    y += 8;

    // Divider between artifacts
    if (idx < entries.length - 1) {
      ensureSpace(5);
      doc.setDrawColor(220, 220, 230);
      doc.setLineWidth(0.15);
      doc.line(margin, y, pw - margin, y);
      y += 8;
    }
  }

  // ─── Disclaimer ────────────────────────────────────────────────────
  ensureSpace(30);
  y += 5;
  doc.setDrawColor(...COLORS.border);
  doc.setLineWidth(0.3);
  doc.line(margin, y, pw - margin, y);
  y += 8;

  doc.setFontSize(8);
  doc.setTextColor(...COLORS.muted);
  doc.setFont("helvetica", "italic");
  const disclaimer = "Disclaimer: This is a concept-level estimate generated by BuildFlow AI. Not for construction documentation. All quantities, costs, and specifications should be verified by qualified professionals before use in any contractual or construction context.";
  const disclaimerLines = doc.splitTextToSize(disclaimer, contentWidth);
  doc.text(disclaimerLines, margin, y);
  y += disclaimerLines.length * 3.5 + 5;

  // ─── Add footers to all pages ───────────────────────────────────────
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.muted);
    doc.text(`Page ${i} of ${totalPages}`, pw / 2, ph - 10, { align: "center" });
    doc.text("Generated by BuildFlow", pw - margin, ph - 10, { align: "right" });
  }

  // ─── Save ──────────────────────────────────────────────────────────
  const filename = `BuildFlow_Report_${new Date().toISOString().split("T")[0]}.pdf`;
  doc.save(filename);
}

// ─── Renderers ─────────────────────────────────────────────────────────────

function renderText(
  doc: jsPDF,
  data: TextArtifactData,
  x: number,
  y: number,
  maxWidth: number
): number {
  const content = data?.content ?? "";
  doc.setFontSize(9);
  doc.setTextColor(60, 60, 80);
  doc.setFont("helvetica", "normal");

  const lines = doc.splitTextToSize(content, maxWidth);
  const maxLines = 40; // Cap very long text
  const displayLines = lines.slice(0, maxLines);

  doc.text(displayLines, x, y);
  y += displayLines.length * 4;

  if (lines.length > maxLines) {
    doc.setTextColor(...COLORS.muted);
    doc.setFontSize(8);
    doc.text(`[...${lines.length - maxLines} more lines — see app for full text]`, x, y);
    y += 4;
  }

  return y;
}

async function renderImage(
  doc: jsPDF,
  data: ImageArtifactData,
  x: number,
  y: number,
  maxWidth: number
): Promise<number> {
  if (!data?.url) {
    doc.setFontSize(9);
    doc.setTextColor(...COLORS.muted);
    doc.text("[No image available]", x, y);
    return y + 6;
  }

  try {
    // Try to embed the image
    const imgWidth = Math.min(maxWidth, 120);
    const imgHeight = imgWidth * 0.65; // ~16:10 aspect

    // Check if page has room
    const pageH = doc.internal.pageSize.getHeight();
    if (y + imgHeight > pageH - 25) {
      doc.addPage();
      y = 20;
    }

    doc.addImage(data.url, "JPEG", x, y, imgWidth, imgHeight);
    y += imgHeight + 3;

    if (data.label) {
      doc.setFontSize(8);
      doc.setTextColor(...COLORS.muted);
      doc.text(data.label, x, y);
      y += 4;
    }
  } catch {
    doc.setFontSize(9);
    doc.setTextColor(...COLORS.muted);
    doc.text("[Image could not be embedded — see app]", x, y);
    y += 6;
  }

  return y;
}

function renderKpis(
  doc: jsPDF,
  data: KpiArtifactData,
  x: number,
  y: number,
  maxWidth: number
): number {
  const metrics = data?.metrics ?? [];
  const colWidth = maxWidth / Math.min(metrics.length, 4);

  for (let i = 0; i < metrics.length; i++) {
    const m = metrics[i];
    const cx = x + (i % 4) * colWidth;

    // New row every 4 KPIs
    if (i > 0 && i % 4 === 0) y += 14;

    doc.setFontSize(14);
    doc.setTextColor(50, 50, 60);
    doc.setFont("helvetica", "bold");
    doc.text(String(m.value), cx, y);

    if (m.unit) {
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.text(m.unit, cx + doc.getTextWidth(String(m.value)) + 1, y);
    }

    doc.setFontSize(8);
    doc.setTextColor(...COLORS.muted);
    doc.setFont("helvetica", "normal");
    doc.text(m.label, cx, y + 4);
  }

  y += 14 + Math.floor((metrics.length - 1) / 4) * 14;
  return y;
}

function renderTable(
  doc: jsPDF,
  data: TableArtifactData,
  x: number,
  y: number,
  maxWidth: number
): number {
  const headers = data?.headers ?? [];
  const rows = data?.rows ?? [];
  if (headers.length === 0) return y;

  // For wide tables, show a simplified view
  const isWide = headers.length > 6;
  const displayHeaders = isWide
    ? [headers[0], headers[2], headers[3], headers[4], headers[headers.length - 1]]
    : headers;
  const displayRows = isWide
    ? rows.map(row => [row[0], row[2], row[3], row[4], row[row.length - 1]])
    : rows;

  const colCount = displayHeaders.length;
  const colWidth = maxWidth / colCount;
  const rowHeight = 5;

  // Header
  doc.setFillColor(240, 240, 245);
  doc.rect(x, y - 3.5, maxWidth, rowHeight + 1, "F");

  doc.setFontSize(7);
  doc.setTextColor(80, 80, 100);
  doc.setFont("helvetica", "bold");
  displayHeaders.forEach((h, i) => {
    const cellX = x + i * colWidth;
    doc.text(String(h).substring(0, 18), cellX + 1, y);
  });
  y += rowHeight + 1;

  // Rows (limit to 30 for PDF)
  doc.setFont("helvetica", "normal");
  doc.setTextColor(60, 60, 80);
  const maxRows = Math.min(displayRows.length, 30);

  for (let r = 0; r < maxRows; r++) {
    const pageH = doc.internal.pageSize.getHeight();
    if (y + rowHeight > pageH - 25) {
      doc.addPage();
      y = 20;
    }

    // Alternating row bg
    if (r % 2 === 0) {
      doc.setFillColor(248, 248, 252);
      doc.rect(x, y - 3.5, maxWidth, rowHeight, "F");
    }

    const row = displayRows[r];
    doc.setFontSize(7);
    row.forEach((cell, i) => {
      const cellX = x + i * colWidth;
      doc.text(String(cell ?? "").substring(0, 20), cellX + 1, y);
    });
    y += rowHeight;
  }

  if (displayRows.length > maxRows) {
    doc.setFontSize(7);
    doc.setTextColor(...COLORS.muted);
    doc.text(`[...${displayRows.length - maxRows} more rows]`, x, y + 3);
    y += 6;
  }

  // Summary line
  const summary = (data as unknown as Record<string, unknown>)?.summary as
    | { grandTotal?: number }
    | undefined;
  if (summary?.grandTotal != null) {
    y += 2;
    doc.setFontSize(9);
    doc.setTextColor(...COLORS.accent);
    doc.setFont("helvetica", "bold");
    doc.text(`Grand Total: $${summary.grandTotal.toLocaleString()}`, x, y);
    y += 5;
  }

  return y;
}

function renderJson(
  doc: jsPDF,
  data: unknown,
  x: number,
  y: number,
  maxWidth: number
): number {
  const jsonStr = JSON.stringify(
    (data as { json?: unknown })?.json ?? data,
    null,
    2
  );
  doc.setFontSize(7);
  doc.setTextColor(60, 60, 80);
  doc.setFont("courier", "normal");

  const lines = doc.splitTextToSize(jsonStr, maxWidth);
  const maxLines = 30;
  const displayLines = lines.slice(0, maxLines);

  doc.text(displayLines, x, y);
  y += displayLines.length * 3;

  if (lines.length > maxLines) {
    doc.setTextColor(...COLORS.muted);
    doc.setFontSize(7);
    doc.text(`[...truncated — ${lines.length - maxLines} more lines]`, x, y);
    y += 4;
  }

  doc.setFont("helvetica", "normal");
  return y;
}
