import type { NodeCatalogueItem } from "@/types/nodes";

export const NODE_CATALOGUE: NodeCatalogueItem[] = [
  // ============================================================
  // INPUT NODES (Blue)
  // ============================================================
  {
    id: "IN-001",
    name: "Text Prompt",
    description: "Free-text input from user (design brief, style description)",
    category: "input",
    icon: "Type",
    inputs: [],
    outputs: [{ id: "text-out", label: "Text", type: "text" }],
    apiEngine: "Native",
    tags: ["text", "prompt", "brief"],
    executionTime: "< 1s",
  },
  {
    id: "IN-002",
    name: "PDF Upload",
    description: "Upload a PDF document (project brief, zoning text, competition doc)",
    category: "input",
    icon: "FileText",
    inputs: [],
    outputs: [
      { id: "pdf-out", label: "PDF", type: "pdf" },
      { id: "meta-out", label: "Metadata", type: "json" },
    ],
    apiEngine: "Native",
    tags: ["pdf", "document", "brief", "upload"],
    executionTime: "< 2s",
  },
  {
    id: "IN-003",
    name: "Image Upload",
    description: "Upload a reference image (sketch, photo, inspiration)",
    category: "input",
    icon: "Image",
    inputs: [],
    outputs: [{ id: "image-out", label: "Image", type: "image" }],
    apiEngine: "Native",
    tags: ["image", "sketch", "photo", "reference"],
    executionTime: "< 2s",
  },
  {
    id: "IN-004",
    name: "IFC Upload",
    description: "Upload an IFC/BIM model file",
    category: "input",
    icon: "Box",
    inputs: [],
    outputs: [{ id: "ifc-out", label: "IFC Model", type: "ifc" }],
    apiEngine: "IFCOpenShell",
    tags: ["ifc", "bim", "model", "revit"],
    executionTime: "< 5s",
  },
  {
    id: "IN-005",
    name: "Parameter Input",
    description: "Numeric parameter entry (floors, height, area, ratios)",
    category: "input",
    icon: "Sliders",
    inputs: [],
    outputs: [{ id: "params-out", label: "Parameters", type: "json" }],
    apiEngine: "Native",
    tags: ["parameters", "sliders", "numeric", "floors", "height"],
    executionTime: "< 1s",
  },
  {
    id: "IN-006",
    name: "Location Input",
    description: "Geographic location entry via address search or map pin",
    category: "input",
    icon: "MapPin",
    inputs: [],
    outputs: [{ id: "geo-out", label: "GeoJSON", type: "geojson" }],
    apiEngine: "Google Maps / OSM",
    tags: ["location", "map", "site", "address", "gis"],
    executionTime: "< 3s",
  },
  {
    id: "IN-007",
    name: "DXF/DWG Upload",
    description: "Upload CAD drawing files",
    category: "input",
    icon: "PenTool",
    inputs: [],
    outputs: [{ id: "cad-out", label: "2D Geometry", type: "geometry" }],
    apiEngine: "CAD Parser",
    tags: ["cad", "dxf", "dwg", "drawing", "autocad"],
    executionTime: "< 5s",
  },

  // ============================================================
  // TRANSFORM / AI NODES (Purple)
  // ============================================================
  {
    id: "TR-001",
    name: "Brief Parser",
    description: "Extract requirements, constraints, and program data from uploaded project brief PDFs",
    category: "transform",
    icon: "ScanText",
    inputs: [{ id: "pdf-in", label: "PDF", type: "pdf" }],
    outputs: [{ id: "text-out", label: "Structured Text", type: "text" }],
    apiEngine: "Azure AI Document Intelligence",
    tags: ["pdf", "parse", "ocr", "extract", "text"],
    executionTime: "< 10s",
  },
  {
    id: "TR-002",
    name: "Requirements Extractor",
    description: "Use AI to convert extracted text into structured building requirements",
    category: "transform",
    icon: "Sparkles",
    inputs: [{ id: "text-in", label: "Text", type: "text" }],
    outputs: [{ id: "req-out", label: "Requirements JSON", type: "json" }],
    apiEngine: "OpenAI GPT",
    tags: ["ai", "requirements", "extract", "program", "constraints"],
    executionTime: "< 15s",
  },
  {
    id: "TR-003",
    name: "Design Brief Analyzer",
    description: "AI-powered analysis that converts text briefs into structured building programs with areas, floors, and spatial requirements",
    category: "transform",
    icon: "Building2",
    inputs: [{ id: "json-in", label: "Requirements", type: "json" }],
    outputs: [
      { id: "text-out", label: "Description", type: "text" },
      { id: "prog-out", label: "Program Blocks", type: "json" },
    ],
    apiEngine: "OpenAI GPT",
    tags: ["ai", "description", "program", "building", "narrative"],
    executionTime: "< 10s",
  },
  {
    id: "TR-004",
    name: "Image Understanding",
    description: "Analyze a reference image and extract design intent and style",
    category: "transform",
    icon: "Eye",
    inputs: [{ id: "image-in", label: "Image", type: "image" }],
    outputs: [
      { id: "text-out", label: "Design Interpretation", type: "text" },
      { id: "feat-out", label: "Extracted Features", type: "json" },
    ],
    apiEngine: "OpenAI Vision",
    tags: ["ai", "vision", "image", "style", "analysis"],
    executionTime: "< 15s",
  },
  {
    id: "TR-005",
    name: "Visualization Style Composer",
    description: "Compose architectural visualization parameters — style, materials, lighting, camera angle for DALL-E 3 rendering",
    category: "transform",
    icon: "Wand2",
    inputs: [
      { id: "geo-in", label: "3D Geometry", type: "geometry" },
      { id: "text-in", label: "Style Text", type: "text" },
    ],
    outputs: [
      { id: "prompt-out", label: "Composed Prompt", type: "text" },
      { id: "ctrl-out", label: "Control Image", type: "image" },
    ],
    apiEngine: "OpenAI GPT-4o-mini",
    tags: ["style", "prompt", "composition", "render", "visualization", "live"],
    executionTime: "< 8s",
  },
  {
    id: "TR-006",
    name: "Zoning Compliance Checker (Coming Soon)",
    description: "AI-assisted zoning guidance and code-aware recommendations (Coming Soon - Not for regulatory compliance)",
    category: "transform",
    icon: "ShieldCheck",
    inputs: [
      { id: "ifc-in", label: "IFC Model", type: "ifc" },
      { id: "rules-in", label: "Zoning Rules", type: "text" },
    ],
    outputs: [{ id: "report-out", label: "Compliance Report", type: "json" }],
    apiEngine: "IFCOpenShell + OpenAI GPT",
    tags: ["compliance", "zoning", "regulations", "check", "bim"],
    executionTime: "2-3 min",
  },
  {
    id: "TR-007",
    name: "Quantity Extractor",
    description: "Extract conceptual quantities from IFC model - ⚠️ SAMPLE DATA for demonstration only",
    category: "transform",
    icon: "Calculator",
    inputs: [{ id: "ifc-in", label: "IFC Model", type: "ifc" }],
    outputs: [{ id: "qty-out", label: "Quantities JSON", type: "json" }],
    apiEngine: "IFCOpenShell",
    tags: ["quantities", "qto", "bim", "ifc", "takeoff"],
    executionTime: "< 20s",
  },
  {
    id: "TR-008",
    name: "BOQ / Cost Mapper",
    description: "Map extracted quantities to cost codes and unit prices",
    category: "transform",
    icon: "DollarSign",
    inputs: [
      { id: "qty-in", label: "Quantities", type: "json" },
    ],
    outputs: [{ id: "boq-out", label: "BOQ Line Items", type: "json" }],
    apiEngine: "OpenAI GPT + Cost DB",
    tags: ["boq", "cost", "estimation", "quantities", "rates"],
    executionTime: "< 20s",
  },
  {
    id: "TR-009",
    name: "BIM Query Engine",
    description: "Answer natural language questions about a BIM model",
    category: "transform",
    icon: "MessageSquare",
    inputs: [
      { id: "ifc-in", label: "IFC Model", type: "ifc" },
      { id: "query-in", label: "Question", type: "text" },
    ],
    outputs: [
      { id: "answer-out", label: "Answer", type: "text" },
      { id: "elements-out", label: "Queried Elements", type: "json" },
    ],
    apiEngine: "IFCOpenShell + OpenAI GPT",
    tags: ["bim", "query", "nlp", "ai", "ifc"],
    executionTime: "< 25s",
  },
  {
    id: "TR-010",
    name: "Delta Comparator",
    description: "Compare two IFC model versions and compute quantity deltas",
    category: "transform",
    icon: "GitCompare",
    inputs: [
      { id: "ifc-v1", label: "IFC v1", type: "ifc" },
      { id: "ifc-v2", label: "IFC v2", type: "ifc" },
    ],
    outputs: [{ id: "delta-out", label: "Delta Report", type: "json" }],
    apiEngine: "IFCOpenShell",
    tags: ["delta", "compare", "versioning", "changes", "ifc"],
    executionTime: "2-3 min",
  },
  {
    id: "TR-011",
    name: "Material / Carbon Inference",
    description: "Infer materials from IFC classification and compute embodied carbon",
    category: "transform",
    icon: "Leaf",
    inputs: [{ id: "qty-in", label: "Quantities + Materials", type: "json" }],
    outputs: [{ id: "carbon-out", label: "Carbon Report", type: "json" }],
    apiEngine: "Database + Calc Engine",
    tags: ["carbon", "sustainability", "materials", "lca", "embodied"],
    executionTime: "< 15s",
  },
  {
    id: "TR-012",
    name: "GIS Context Loader",
    description: "Load site context data (terrain, nearby buildings, lot boundary)",
    category: "transform",
    icon: "Globe",
    inputs: [{ id: "geo-in", label: "GeoJSON Location", type: "geojson" }],
    outputs: [
      { id: "ctx-geo-out", label: "Context Mesh", type: "geometry" },
      { id: "site-out", label: "Site Data", type: "json" },
    ],
    apiEngine: "Google Maps 3D / OSM / Mapbox",
    tags: ["gis", "context", "site", "terrain", "map"],
    executionTime: "< 20s",
  },

  // ============================================================
  // GENERATE / GEOMETRY NODES (Green)
  // ============================================================
  {
    id: "GN-001",
    name: "Massing Generator",
    description: "Generate BIM-compatible 3D massing models from building description or parameters",
    category: "generate",
    icon: "Box",
    inputs: [{ id: "req-in", label: "Requirements", type: "json" }],
    outputs: [
      { id: "geo-out", label: "3D Massing", type: "geometry" },
      { id: "kpi-out", label: "KPIs", type: "json" },
    ],
    apiEngine: "Rhino.Compute",
    tags: ["massing", "3d", "geometry", "building", "volume"],
    executionTime: "2-3 min",
  },
  {
    id: "GN-002",
    name: "Variant Generator",
    description: "Generate N design variants by systematically varying parameters",
    category: "generate",
    icon: "Layers",
    inputs: [
      { id: "params-in", label: "Parameter Ranges", type: "json" },
      { id: "geo-in", label: "Base Geometry", type: "geometry" },
    ],
    outputs: [
      { id: "variants-out", label: "3D Variants", type: "geometry" },
      { id: "metrics-out", label: "Metrics per Variant", type: "json" },
    ],
    apiEngine: "Rhino.Compute",
    tags: ["variants", "options", "design", "exploration", "parametric"],
    executionTime: "< 60s",
  },
  {
    id: "GN-003",
    name: "Concept Render Generator",
    description: "Generate photorealistic architectural concept renders from building descriptions with 4 view types: exterior, floor plan, site plan, interior",
    category: "generate",
    icon: "Palette",
    inputs: [
      { id: "ctrl-in", label: "Control Image", type: "image" },
      { id: "prompt-in", label: "Style Prompt", type: "text" },
    ],
    outputs: [{ id: "images-out", label: "Concept Images", type: "image" }],
    apiEngine: "OpenAI DALL·E 3",
    tags: ["image", "render", "visualization", "concept", "ai", "exterior", "floor plan", "site plan", "interior"],
    executionTime: "2-3 min",
    viewType: "exterior",
  },
  {
    id: "GN-004",
    name: "Floor Plan Generator",
    description: "Generate 2D floor plan layouts from room program and footprint",
    category: "generate",
    icon: "LayoutGrid",
    inputs: [{ id: "prog-in", label: "Room Program", type: "json" }],
    outputs: [
      { id: "plan-out", label: "Floor Plan", type: "geometry" },
      { id: "img-out", label: "Annotated Plan Image", type: "image" },
    ],
    apiEngine: "OR-Tools + Rhino.Compute",
    tags: ["floor plan", "layout", "rooms", "2d", "planning"],
    executionTime: "< 45s",
  },
  {
    id: "GN-005",
    name: "Façade Generator",
    description: "Generate parametric façade patterns on massing surfaces",
    category: "generate",
    icon: "Grid",
    inputs: [
      { id: "geo-in", label: "Massing", type: "geometry" },
      { id: "params-in", label: "Style Parameters", type: "json" },
    ],
    outputs: [{ id: "facade-out", label: "Detailed Façade Model", type: "geometry" }],
    apiEngine: "Rhino.Compute (Grasshopper)",
    tags: ["facade", "cladding", "parametric", "detail", "3d"],
    executionTime: "< 60s",
  },
  {
    id: "GN-006",
    name: "IFC-to-Web Converter",
    description: "Convert IFC model to web-viewable format for inline canvas viewing",
    category: "generate",
    icon: "Monitor",
    inputs: [{ id: "ifc-in", label: "IFC Model", type: "ifc" }],
    outputs: [{ id: "web-out", label: "Web 3D Model", type: "geometry" }],
    apiEngine: "xeokit",
    tags: ["ifc", "viewer", "web", "3d", "bim"],
    executionTime: "< 20s",
  },

  {
    id: "GN-007",
    name: "Image to 3D (SAM 3D)",
    description: "Convert a building image into a 3D model (GLB/PLY) using Meta's SAM 3D via fal.ai",
    category: "generate",
    icon: "Box",
    inputs: [{ id: "image-in", label: "Building Image", type: "image" }],
    outputs: [
      { id: "glb-out", label: "3D Model (GLB)", type: "geometry" },
      { id: "ply-out", label: "Gaussian Splat (PLY)", type: "binary" },
    ],
    apiEngine: "fal.ai SAM 3D",
    tags: ["3d", "sam3d", "image-to-3d", "glb", "ply", "meta", "building", "mesh"],
    executionTime: "< 30s",
  },
  {
    id: "GN-008",
    name: "Text to 3D Generator",
    description: "Generate a realistic 3D building model from text — chains DALL-E 3 image generation with SAM 3D conversion in one step",
    category: "generate",
    icon: "Boxes",
    inputs: [
      { id: "text-in", label: "Building Description", type: "text" },
    ],
    outputs: [
      { id: "glb-out", label: "3D Model (GLB)", type: "geometry" },
      { id: "image-out", label: "Generated Image", type: "image" },
    ],
    apiEngine: "OpenAI DALL·E 3 + fal.ai SAM 3D",
    tags: ["text-to-3d", "3d", "ai", "dall-e", "sam3d", "building", "generate", "mesh", "glb"],
    executionTime: "< 60s",
  },

  // ============================================================
  // EXPORT / OUTPUT NODES (Amber)
  // ============================================================
  {
    id: "EX-001",
    name: "IFC Exporter (Coming Soon)",
    description: "Export BIM-compatible massing as IFC file (Coming Soon - Basic conceptual export only)",
    category: "export",
    icon: "Download",
    inputs: [
      { id: "geo-in", label: "3D Geometry", type: "geometry" },
      { id: "meta-in", label: "Metadata", type: "json" },
    ],
    outputs: [{ id: "ifc-out", label: "IFC File", type: "ifc" }],
    apiEngine: "IFCOpenShell",
    tags: ["ifc", "export", "bim", "file", "download"],
    executionTime: "< 15s",
  },
  {
    id: "EX-002",
    name: "BOQ / Spreadsheet Exporter",
    description: "Export bill of quantities or cost estimate as XLSX/CSV",
    category: "export",
    icon: "Table",
    inputs: [{ id: "boq-in", label: "BOQ Data", type: "json" }],
    outputs: [{ id: "xlsx-out", label: "XLSX + CSV", type: "csv" }],
    apiEngine: "SpreadsheetML / openpyxl",
    tags: ["boq", "excel", "spreadsheet", "export", "quantities"],
    executionTime: "< 10s",
  },
  {
    id: "EX-003",
    name: "PDF Report Generator",
    description: "Generate a formatted PDF report (compliance, cost summary, design brief)",
    category: "export",
    icon: "FileOutput",
    inputs: [
      { id: "data-in", label: "Report Data", type: "json" },
      { id: "img-in", label: "Images (optional)", type: "image" },
    ],
    outputs: [{ id: "pdf-out", label: "PDF Report", type: "pdf" }],
    apiEngine: "ReportLab / WeasyPrint",
    tags: ["pdf", "report", "export", "document"],
    executionTime: "< 15s",
  },
  {
    id: "EX-004",
    name: "Speckle Publisher",
    description: "Publish 3D model or data to Speckle for sharing and versioning",
    category: "export",
    icon: "Share2",
    inputs: [{ id: "geo-in", label: "3D Model or IFC", type: "geometry" }],
    outputs: [{ id: "url-out", label: "Speckle Commit URL", type: "text" }],
    apiEngine: "Speckle SDK",
    tags: ["speckle", "share", "collaborate", "versioning", "3d"],
    executionTime: "< 20s",
  },
  {
    id: "EX-005",
    name: "Dashboard Publisher",
    description: "Publish workflow outputs to an analytics dashboard",
    category: "export",
    icon: "BarChart3",
    inputs: [{ id: "metrics-in", label: "Metrics JSON", type: "json" }],
    outputs: [{ id: "dash-out", label: "Dashboard Link", type: "text" }],
    apiEngine: "Power BI / Custom Dashboard",
    tags: ["dashboard", "analytics", "kpi", "reporting"],
    executionTime: "< 10s",
  },
  {
    id: "EX-006",
    name: "Image Exporter",
    description: "Export generated images in high-resolution format",
    category: "export",
    icon: "ImageDown",
    inputs: [{ id: "images-in", label: "Images", type: "image" }],
    outputs: [{ id: "files-out", label: "JPEG/PNG Files", type: "binary" }],
    apiEngine: "Native",
    tags: ["image", "export", "download", "hires", "jpeg", "png"],
    executionTime: "< 5s",
  },
];

export const NODE_CATALOGUE_MAP = new Map(
  NODE_CATALOGUE.map((node) => [node.id, node])
);

export const NODES_BY_CATEGORY = {
  input: NODE_CATALOGUE.filter((n) => n.category === "input"),
  transform: NODE_CATALOGUE.filter((n) => n.category === "transform"),
  generate: NODE_CATALOGUE.filter((n) => n.category === "generate"),
  export: NODE_CATALOGUE.filter((n) => n.category === "export"),
};

export const CATEGORY_CONFIG = {
  input: {
    label: "Input",
    color: "#00F5FF",
    bgColor: "rgba(0, 245, 255, 0.06)",
    borderColor: "rgba(0, 245, 255, 0.3)",
    description: "Data sources that feed into your workflow",
  },
  transform: {
    label: "Transform / AI",
    color: "#B87333",
    bgColor: "rgba(184, 115, 51, 0.06)",
    borderColor: "rgba(184, 115, 51, 0.3)",
    description: "AI-powered processing and data transformation",
  },
  generate: {
    label: "Generate / Geometry",
    color: "#FFBF00",
    bgColor: "rgba(255, 191, 0, 0.06)",
    borderColor: "rgba(255, 191, 0, 0.3)",
    description: "3D modeling, image generation, and variant creation",
  },
  export: {
    label: "Export / Output",
    color: "#4FC3F7",
    bgColor: "rgba(79, 195, 247, 0.06)",
    borderColor: "rgba(79, 195, 247, 0.3)",
    description: "File exports, reports, and delivery",
  },
} as const;

/** Nodes that use real API calls (not mock/sample data) */
export const LIVE_NODES = new Set(['TR-003', 'TR-007', 'TR-008', 'GN-003', 'GN-007', 'GN-008', 'EX-002']);
